name: Push to S3

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.A_AWS_SECRET }}
          aws-secret-access-key: ${{ secrets.A_AWS_ACCESS }}
          aws-region: us-east-1
      - name: copy files to S3 bucket
        run: |
          aws s3 cp mee.txt "s3://meena418/"
